spring.application.name=hotel-manager

# ==============================================================
# 1. ????????? ???? ?????? (Labs 3-5)
# ==============================================================
# ????? ? ?????? ??????? ?? ?????????? ????????? (Environment Variables)
# ??? ?????????? ???????????? (Lab 4)
spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ==============================================================
# 2. ????????? JPA / HIBERNATE
# ==============================================================
# update - ????????????? ????????? ????? ?? ??? ???????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ????????? Open Session In View ??? ?????????????? ??????? ??????????
spring.jpa.open-in-view=false

# ==============================================================
# 3. ????????? ??????
# ==============================================================
# ????? ? Postman ?????? ????? ?????? (????????, "Booking not found")
server.error.include-message=always

# ==============================================================
# 4. ????????? HTTPS / SSL (Lab 6)
# ==============================================================
# ?????? ???? ?? ??????????? ??? HTTPS ? Java
server.port=8443

# ???????? SSL
server.ssl.enabled=true

# ???? ? ????????? ?????? (???? ?????? ?????? ? src/main/resources)
server.ssl.key-store=classpath:hotel-server.jks

# ??? ????????? (JKS - Java KeyStore)
server.ssl.key-store-type=JKS

# ?????? ?? ????????? (??? ??, ??? ?? ???????? ? ??????? ?????????)
server.ssl.key-store-password=securePass123!

# ????? ????? ??????? ?????? ????????? (?? ??????? ?????????: alias serverKey)
server.ssl.key-alias=serverKey