name: Java CI with Maven

on:
  push:
    branches: [ "main", "lab_6" ]
  pull_request:
    branches: [ "main", "lab_6" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # 1. ВОССТАНАВЛИВАЕМ КЛЮЧ ИЗ СЕКРЕТОВ (Требование задания)
      - name: Decode Keystore
        run: |
          # Декодируем base64 строку обратно в файл
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > src/main/resources/hotel-server.jks

      # 2. СБОРКА И ТЕСТИРОВАНИЕ
      # Мы убрали -DskipTests. Теперь maven запустит тесты.
      # Важно: Чтобы тесты прошли, либо удалите папку src/test,
      # либо убедитесь, что тесты не требуют реальной БД.
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        env:
          # Передаем пароль от ключа в переменную окружения (если используете её в application.properties)
          SERVER_SSL_KEY_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hotel-app-jar
          path: target/*.jar